paths: 
  /api/auth/products/:
    get:
      summary: Todos los Products
      tags:
        - Product
    post:
      summary: Cargar un Products
      tags:
        - Product
  /api/auth/products/{pid}:
    get:
      summary: Un producto en particular
      tags:
        - Product
    put:
      summary: Modificar un producto en particular
      tags:
        - Product
    delete:
      summary: Borrar un producto en particular
      tags:
        - Product
  /api/auth/products/mocking/products:
    get:
      summary: Products mocking
      tags:
        - Product